arrow==1.2.2
binaryornot==0.4.4
certifi==2022.6.15
chardet==5.0.0
charset-normalizer==2.1.0
click==8.1.3
cookiecutter==1.7.3
idna==3.3
Jinja2==3.1.2
jinja2-time==0.2.0
MarkupSafe==2.1.1
poyo==0.5.0
python-dateutil==2.8.2
python-slugify==6.1.2
requests==2.28.1
six==1.16.0
text-unidecode==1.3
urllib3==1.26.10
